# Generated by Django 6.0.7 on 2026-07-30 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InternshipPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('lab', models.CharField(blank=True, default='', max_length=150)),
                ('description', models.TextField()),
                ('eligibility', models.TextField(blank=True, default='')),
                ('duration_weeks', models.PositiveIntegerField(default=8)),
                ('stipend', models.PositiveIntegerField(default=0, help_text='Monthly stipend in INR.')),
                ('application_deadline', models.DateField()),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('required_documents', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
