# Generated by Django 6.0.7 on 2026-07-30 10:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('postings', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='internshipposting',
            name='created_by',
            field=models.ForeignKey(limit_choices_to={'role__in': ['faculty', 'institution_admin']}, on_delete=django.db.models.deletion.CASCADE, related_name='postings_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='internshipposting',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postings', to='users.institution'),
        ),
    ]
