# Generated by Django 6.0.7 on 2026-07-31 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnumatiConnectionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('screening', 'Screening'), ('admission_active', 'Admission (active, bidirectional)')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending (created in SRIP, not yet confirmed live)'), ('live', 'Live'), ('closed', 'Closed'), ('failed', 'Failed (Anumati call errored)')], default='pending', max_length=15)),
                ('anumati_connection_id', models.CharField(blank=True, default='', max_length=64)),
                ('anumati_connection_type_id', models.CharField(blank=True, default='', max_length=64)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('error_detail', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anumati_records', to='applications.application')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
