# Generated by Django 6.0.7 on 2026-07-31 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='anumati_admissions_locker_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='institution',
            name='anumati_username',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='user',
            name='anumati_locker_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
