# Generated by Django 6.0.7 on 2026-08-05 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_institution_anumati_admissions_locker_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='anumati_linked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='anumati_password_encrypted',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='anumati_linked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
