# Generated by Django 6.0.7 on 2026-08-05 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_institution_anumati_linked_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='anumati_username',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
