# Generated by Django 6.0.7 on 2026-08-06 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_anumati_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='anumati_verified',
            field=models.BooleanField(default=False),
        ),
    ]
