# Generated by Django 6.0.7 on 2026-08-11 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_anumati_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='anumati_admissions_locker_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='institution',
            name='anumati_linked_via_oauth',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='institution',
            name='anumati_refresh_token_encrypted',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
